package software.momento.kotlin.sdk.errors

public enum class MomentoErrorCode(public val errorCode: String) {
    INVALID_ARGUMENT_ERROR("INVALID_ARGUMENT_ERROR"),
    UNKNOWN_SERVICE_ERROR("UNKNOWN_SERVICE_ERROR"),
    ALREADY_EXISTS_ERROR("ALREADY_EXISTS_ERROR"),
    NOT_FOUND_ERROR("NOT_FOUND_ERROR"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    PERMISSION_ERROR("PERMISSION_ERROR"),
    AUTHENTICATION_ERROR("AUTHENTICATION_ERROR"),
    CANCELLED_ERROR("CANCELLED_ERROR"),
    LIMIT_EXCEEDED_ERROR("LIMIT_EXCEEDED_ERROR"),
    BAD_REQUEST_ERROR("BAD_REQUEST_ERROR"),
    TIMEOUT_ERROR("TIMEOUT_ERROR"),
    SERVER_UNAVAILABLE("SERVER_UNAVAILABLE"),
    CLIENT_RESOURCE_EXHAUSTED("CLIENT_RESOURCE_EXHAUSTED"),
    FAILED_PRECONDITION_ERROR("FAILED_PRECONDITION_ERROR"),
    UNKNOWN_ERROR("UNKNOWN_ERROR")
}
